export default [
  { value: 'London', label: 'London' },
  { value: 'San Francisco', label: 'San Francisco' },
  { value: 'New York', label: 'New York' },
  { value: 'Sydney', label: 'Sydney' },
  { value: 'Philadelphia', label: 'Philadelphia' },
  { value: 'Manchester', label: 'Manchester' },
  { value: 'Houston', label: 'Houston' },
  { value: 'Birmingham', label: 'Birmingham' },
  { value: 'Los Angeles', label: 'Los Angeles' },
  { value: 'Berlin', label: 'Berlin' },
  { value: 'Chicago', label: 'Chicago' },
  { value: 'Tokyo', label: 'Tokyo' },
  { value: 'Beijing', label: 'Beijing' },
  { value: 'Mexico City', label: 'Mexico City' },
  { value: 'Osaka', label: 'Osaka' },
  { value: 'Bristol', label: 'Bristol' },
  { value: 'Mumbai', label: 'Mumbai' },
  { value: 'Glasgow', label: 'Glasgow' },
  { value: 'Amsterdam', label: 'Amsterdam' },
  { value: 'Johannesburg', label: 'Johannesburg' },
  { value: 'Rio de Janeiro', label: 'Rio de Janeiro' },
  { value: 'Shanghai', label: 'Shanghai' },
  { value: 'New Delhi', label: 'New Delhi' },
  { value: 'Jakarta', label: 'Jakarta' },
  { value: 'Seoul', label: 'Seoul' },
  { value: 'São Paulo', label: 'São Paulo' },
  { value: 'Moscow', label: 'Moscow' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'San Diego', label: 'San Diego' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'Dallas', label: 'Dallas' },
  { value: 'Indianapolis', label: 'Indianapolis' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'Montréal', label: 'Montréal' },
  { value: 'Jacksonville', label: 'Jacksonville' },
  { value: 'Austin', label: 'Austin' },
  { value: 'Kiev', label: 'Kiev' },
  { value: 'Phoenix', label: 'Phoenix' },
  { value: 'Madrid', label: 'Madrid' },
  { value: 'Toronto', label: 'Toronto' },
  { value: 'Fort Worth', label: 'Fort Worth' },
  { value: 'Guangzhou', label: 'Guangzhou' },
  { value: 'Columbus', label: 'Columbus' },
  { value: 'Memphis', label: 'Memphis' },
  { value: 'Washington DC', label: 'Washington DC' },
  { value: 'Paris', label: 'Paris' },
  { value: 'Munich', label: 'Munich' },
  { value: 'Brisbane', label: 'Brisbane' },
  { value: 'Rome', label: 'Rome' },
  { value: 'Milwaukee', label: 'Milwaukee' },
  { value: 'Bradford', label: 'Bradford' },
  { value: 'Liverpool', label: 'Liverpool' },
  { value: 'Wakefield', label: 'Wakefield' },
  { value: 'Istanbul', label: 'Istanbul' },
  { value: 'El Paso', label: 'El Paso' },
  { value: 'Seattle', label: 'Seattle' },
  { value: 'Baltimore', label: 'Baltimore' },
  { value: 'Las Vegas', label: 'Las Vegas' },
  { value: 'Melbourne', label: 'Melbourne' },
  { value: 'Buenos Aires', label: 'Buenos Aires' },
  { value: 'Boston', label: 'Boston' },
  { value: 'Nashville', label: 'Nashville' },
  { value: 'Edinburgh', label: 'Edinburgh' },
  { value: 'Perth', label: 'Perth' },
  { value: 'Karachi', label: 'Karachi' },
  { value: 'Hamburg', label: 'Hamburg' },
  { value: 'Dubai', label: 'Dubai' },
  { value: 'Leeds', label: 'Leeds' },
  { value: 'Sheffield', label: 'Sheffield' },
  { value: 'Adelaide', label: 'Adelaide' },
  { value: 'Charlotte', label: 'Charlotte' },
  { value: 'Detroit', label: 'Detroit' },
  { value: 'Louisville', label: 'Louisville' },
  { value: 'Barcelona', label: 'Barcelona' },
  { value: 'Denver', label: 'Denver' },
  { value: 'Portland', label: 'Portland' },
  { value: 'Oklahoma City', label: 'Oklahoma City' },
  { value: 'Cardiff', label: 'Cardiff' },
  { value: 'Kolkata', label: 'Kolkata' },
  { value: 'Cairo', label: 'Cairo' },
  { value: 'Virginia Beach', label: 'Virginia Beach' },
  { value: 'Kinshasa', label: 'Kinshasa' },
  { value: 'Honolulu', label: 'Honolulu' },
  { value: 'Tehrān', label: 'Tehrān' },
  { value: 'Colorado Springs', label: 'Colorado Springs' },
  { value: 'Auckland', label: 'Auckland' },
  { value: 'Dongguan', label: 'Dongguan' },
  { value: 'Sacramento', label: 'Sacramento' },
  { value: 'Kansas City', label: 'Kansas City' },
  { value: 'Fresno', label: 'Fresno' },
  { value: 'Bangkok', label: 'Bangkok' },
  { value: 'Ho Chi Minh City', label: 'Ho Chi Minh City' },
  { value: 'Mesa', label: 'Mesa' },
  { value: 'Atlanta', label: 'Atlanta' },
  { value: 'Bangalore', label: 'Bangalore' },
  { value: 'Lima', label: 'Lima' },
  { value: 'Albuquerque', label: 'Albuquerque' },
  { value: 'Tucson', label: 'Tucson' },
  { value: 'Lagos', label: 'Lagos' },
  { value: 'Long Beach', label: 'Long Beach' },
  { value: 'Shenzhen', label: 'Shenzhen' },
  { value: 'Bogotá', label: 'Bogotá' },
  { value: 'Omaha', label: 'Omaha' },
  { value: 'Raleigh', label: 'Raleigh' },
  { value: 'Miami', label: 'Miami' },
  { value: 'Exeter', label: 'Exeter' },
  { value: 'Hà Nội', label: 'Hà Nội' },
  { value: 'Casablanca', label: 'Casablanca' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Yokohama', label: 'Yokohama' },
  { value: 'Nairobi', label: 'Nairobi' },
  { value: 'Tianjin', label: 'Tianjin' },
  { value: 'Dhaka', label: 'Dhaka' },
  { value: 'Pyongyang', label: 'Pyongyang' },
  { value: 'Addis Ababa', label: 'Addis Ababa' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Santa Cruz', label: 'Santa Cruz' },
  { value: 'Dublin', label: 'Dublin' },
  { value: 'Budapest', label: 'Budapest' },
  { value: 'Milan', label: 'Milan' },
  { value: 'Cambridge', label: 'Cambridge' },
  { value: 'Oxford', label: 'Oxford' },
  { value: 'Vienna', label: 'Vienna' },
  { value: 'Brussels', label: 'Brussels' },
  { value: 'Cologne', label: 'Cologne' },
  { value: 'Riyadh', label: 'Riyadh' },
  { value: 'Damascus', label: 'Damascus' },
  { value: 'Ankara', label: 'Ankara' },
  { value: 'Little Rock', label: 'Little Rock' },
  { value: 'Wilmington', label: 'Wilmington' },
  { value: 'Santiago', label: 'Santiago' },
  { value: 'Birmingham', label: 'Birmingham' },
  { value: 'Baghdad', label: 'Baghdad' },
  { value: 'Boise', label: 'Boise' },
  { value: 'Anchorage', label: 'Anchorage' },
  { value: 'Athens', label: 'Athens' },
  { value: 'Santorini', label: 'Santorini' },
  { value: 'Reykjavík', label: 'Reykjavík' },
  { value: 'Sofia', label: 'Sofia' },
  { value: 'Prague', label: 'Prague' },
  { value: 'Zagreb', label: 'Zagreb' },
  { value: 'Oslo', label: 'Oslo' },
  { value: 'Copenhagen', label: 'Copenhagen' },
  { value: 'Bucharest', label: 'Bucharest' },
  { value: 'Torino', label: 'Torino' },
  { value: 'Stockholm', label: 'Stockholm' },
  { value: 'Naples', label: 'Naples' },
  { value: 'Warsaw', label: 'Warsaw' },
  { value: 'Bridgeport', label: 'Bridgeport' },
  { value: 'Wichita', label: 'Wichita' },
  { value: 'Richmond', label: 'Richmond' },
  { value: 'New Orleans', label: 'New Orleans' },
  { value: 'Calgary', label: 'Calgary' },
  { value: 'Edmonton', label: 'Edmonton' },
  { value: 'St Petersburg', label: 'St Petersburg' },
  { value: 'Manila', label: 'Manila' },
  { value: 'Vancouver', label: 'Vancouver' },
  { value: 'Maracaibo', label: 'Maracaibo' },
  { value: 'Caracas', label: 'Caracas' },
  { value: 'Cheyenne', label: 'Cheyenne' },
  { value: 'Charleston', label: 'Charleston' },
  { value: 'Santander', label: 'Santander' },
  { value: 'İzmir', label: 'İzmir' },
  { value: 'Toulouse', label: 'Toulouse' },
  { value: 'Bordeaux', label: 'Bordeaux' },
  { value: 'Wuhan', label: 'Wuhan' },
  { value: 'Marseille', label: 'Marseille' },
  { value: 'Lille', label: 'Lille' },
  { value: 'Ahmedabad', label: 'Ahmedabad' },
  { value: 'Lyon', label: 'Lyon' },
  { value: 'Nice', label: 'Nice' },
  { value: 'Lahore', label: 'Lahore' },
  { value: 'Belfast', label: 'Belfast' },
  { value: 'Bremen', label: 'Bremen' },
  { value: 'Stoke-on-Trent', label: 'Stoke-on-Trent' },
  { value: 'Fargo', label: 'Fargo' },
  { value: 'Sendai', label: 'Sendai' },
  { value: 'Truro', label: 'Truro' },
  { value: 'Preston', label: 'Preston' },
  { value: 'Sunderland', label: 'Sunderland' },
  { value: 'Lisbon', label: 'Lisbon' },
  { value: 'Phuket', label: 'Phuket' },
  { value: 'Palm Springs', label: 'Palm Springs' },
  { value: 'Leicester', label: 'Leicester' },
  { value: 'Stuttgart', label: 'Stuttgart' },
  { value: 'Coventry', label: 'Coventry' },
  { value: 'Gothenburg', label: 'Gothenburg' },
  { value: 'Hanover', label: 'Hanover' },
  { value: 'St. Louis', label: 'St. Louis' },
  { value: 'Salvador', label: 'Salvador' },
  { value: 'Plymouth', label: 'Plymouth' },
  { value: 'Lake Tahoe', label: 'Lake Tahoe' },
  { value: 'Nuremberg', label: 'Nuremberg' },
  { value: 'Mountain View', label: 'Mountain View' },
  { value: 'Kawasaki', label: 'Kawasaki' },
  { value: 'Kyoto', label: 'Kyoto' },
  { value: 'Kobe', label: 'Kobe' },
  { value: 'Hangzhou', label: 'Hangzhou' },
  { value: 'Blackpool', label: 'Blackpool' },
  { value: 'Yangon', label: 'Yangon' },
  { value: 'Bakersfield', label: 'Bakersfield' },
  { value: 'Salt Lake City', label: 'Salt Lake City' },
  { value: 'Geneva', label: 'Geneva' },
  { value: 'Portland', label: 'Portland' },
  { value: 'Reading', label: 'Reading' },
  { value: 'Durban', label: 'Durban' },
  { value: 'Saitama', label: 'Saitama' },
  { value: 'Brighton', label: 'Brighton' },
  { value: 'Dresden', label: 'Dresden' },
  { value: 'Ajaccio', label: 'Ajaccio' },
  { value: 'Pune', label: 'Pune' },
  { value: 'Mombasa', label: 'Mombasa' },
  { value: 'Providence', label: 'Providence' },
  { value: 'Chennai', label: 'Chennai' },
  { value: 'Kharkiv', label: 'Kharkiv' },
  { value: 'Helsinki', label: 'Helsinki' },
  { value: 'Taipei', label: 'Taipei' },
  { value: 'Essen', label: 'Essen' },
  { value: 'St Ives', label: 'St Ives' },
  { value: 'Aberdeen', label: 'Aberdeen' },
  { value: 'Oakland', label: 'Oakland' },
  { value: 'Sapporo', label: 'Sapporo' },
  { value: 'Ipswich', label: 'Ipswich' },
  { value: 'Norwich', label: 'Norwich' },
  { value: 'Christchurch', label: 'Christchurch' },
  { value: 'Surat', label: 'Surat' },
  { value: 'Busan', label: 'Busan' },
  { value: 'Manchester', label: 'Manchester' },
  { value: 'Hiroshima', label: 'Hiroshima' },
  { value: 'Northampton', label: 'Northampton' },
  { value: 'Leipzig', label: 'Leipzig' },
  { value: 'Southend-on-Sea', label: 'Southend-on-Sea' },
  { value: 'The Hague', label: 'The Hague' },
  { value: 'Minsk', label: 'Minsk' },
  { value: 'Salford', label: 'Salford' },
  { value: 'Kirkwall', label: 'Kirkwall' },
  { value: 'Swansea', label: 'Swansea' },
  { value: 'Penzance', label: 'Penzance' },
  { value: 'Ibadan', label: 'Ibadan' },
  { value: 'Billings', label: 'Billings' },
  { value: 'Alexandria', label: 'Alexandria' },
  { value: 'Newcastle', label: 'Newcastle' },
  { value: 'Jackson', label: 'Jackson' },
  { value: 'Sioux Falls', label: 'Sioux Falls' },
  { value: 'Nagoya', label: 'Nagoya' },
  { value: 'Swindon', label: 'Swindon' },
  { value: 'Brasília', label: 'Brasília' },
  { value: 'Dundee', label: 'Dundee' },
  { value: 'Kano', label: 'Kano' },
  { value: 'Kitakyushu', label: 'Kitakyushu' },
  { value: 'Denpasar', label: 'Denpasar' },
  { value: 'Boulder', label: 'Boulder' },
  { value: 'Minneapolis', label: 'Minneapolis' },
  { value: 'Frankfurt', label: 'Frankfurt' },
  { value: 'Falmouth', label: 'Falmouth' },
  { value: 'Middlesbrough', label: 'Middlesbrough' },
  { value: 'Rhyl', label: 'Rhyl' },
  { value: 'Bournemouth', label: 'Bournemouth' },
  { value: 'Fukuoka', label: 'Fukuoka' },
  { value: 'Newark', label: 'Newark' },
  { value: 'Manukau', label: 'Manukau' },
  { value: 'Luton', label: 'Luton' },
  { value: 'Wellington', label: 'Wellington' },
  { value: 'Abidjan', label: 'Abidjan' },
  { value: 'Kingston upon Hull', label: 'Kingston upon Hull' },
  { value: 'Des Moines', label: 'Des Moines' },
  { value: 'Windhoek', label: 'Windhoek' },
  { value: 'Calvi', label: 'Calvi' },
  { value: 'Venice', label: 'Venice' },
  { value: 'Santa Cruz de Tenerife', label: 'Santa Cruz de Tenerife' },
  { value: 'Chengdu', label: 'Chengdu' },
  { value: 'York', label: 'York' },
  { value: 'Kuala Lumpur', label: 'Kuala Lumpur' },
  { value: 'Portsmouth', label: 'Portsmouth' },
  { value: 'Sidmouth', label: 'Sidmouth' },
  { value: 'Burlington', label: 'Burlington' },
  { value: 'Santa Fe', label: 'Santa Fe' },
  { value: 'Zurich', label: 'Zurich' },
  { value: 'Nottingham', label: 'Nottingham' },
  { value: 'Derby', label: 'Derby' },
  { value: 'Huddersfield', label: 'Huddersfield' },
  { value: 'Dortmund', label: 'Dortmund' },
  { value: 'Wolverhampton', label: 'Wolverhampton' },
  { value: 'Cape Town', label: 'Cape Town' },
  { value: 'Düsseldorf', label: 'Düsseldorf' },
  { value: 'Columbia', label: 'Columbia' },
];
